### ISSUE TITLE
Clear Logger Memory - Confirmation Needed

### ISSUE THREAD

**Issue by aprsandrew** [aprsworld/rdlWC#3]
When the "Clear Logger Memory" button is clicked, it instantly sends the command to erase the data logger's internal memory.  This could potentially be an issue if a customer accidentally clicks that button when they're trying to click the "Download Now" button.  The buttons are right next to each other.  

It may be better to have it pop up with a dialog box with something like the following text:

**WARNING!  This will erase all recorded data from the data logger's internal memory.  This should be done on a regular basis, but make sure you have downloaded a valid copy of the data before doing so.  Are you sure you want to do this?   (YES / NO)**

**Comment by Cdetviler** [comment]
Confirmation dialog added with the text outlined in the original issue.
