### ISSUE TITLE
Crash when rdLogger dataflash is over the limit

### ISSUE THREAD

**Issue by aprsandrew** [aprsworld/rdlWC#4]
When rdLogger data flash is over 4096 pages (ie, 8000 / 4096 full), software crashes when trying to download the data.  (Error message something like "array out of range" if I recall correctly)  

Should limit software to downloading the 4096 pages.

**Comment by aprsandrew** [comment]
This could be done as a line item in the config_default.ini file such as:
max_internal_pages=4096

so that if the rdLogger architecture ever changed to include more pages than that, it could be configured accordingly without modifying/recompiling the software.  (Just a thought.  Not sure if that's relevant or would ever be a possibility.)

If it was done like this, the array causing the crash would have to be dimensioned accordingly for the configured size.

**Comment by Cdetviler** [comment]
I have added an attribute to the inifile that is automatically set to 4096 when setup is run. I tested with a unit that had 11000 pages and it correctly stopped at the default value of 4096. I also tested with a value of 2000 and it only grabbed the first 2000 pages.
